// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simplex
NumericVector simplex(Function r_func, int n1, int p, NumericVector index_vec, NumericMatrix X_mat, NumericVector z_vec, NumericVector mu_vec, NumericMatrix sigma_mat, NumericVector start_vec, double EPSILON, double scale);
RcppExport SEXP _PUGMM_simplex(SEXP r_funcSEXP, SEXP n1SEXP, SEXP pSEXP, SEXP index_vecSEXP, SEXP X_matSEXP, SEXP z_vecSEXP, SEXP mu_vecSEXP, SEXP sigma_matSEXP, SEXP start_vecSEXP, SEXP EPSILONSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type r_func(r_funcSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type index_vec(index_vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_mat(X_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_vec(z_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_vec(mu_vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma_mat(sigma_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type start_vec(start_vecSEXP);
    Rcpp::traits::input_parameter< double >::type EPSILON(EPSILONSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex(r_func, n1, p, index_vec, X_mat, z_vec, mu_vec, sigma_mat, start_vec, EPSILON, scale));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PUGMM_simplex", (DL_FUNC) &_PUGMM_simplex, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_PUGMM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
