# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simplex <- function(r_func, n1, p, index_vec, X_mat, z_vec, mu_vec, sigma_mat, start_vec, EPSILON, scale) {
    .Call(`_PUGMM_simplex`, r_func, n1, p, index_vec, X_mat, z_vec, mu_vec, sigma_mat, start_vec, EPSILON, scale)
}

